# Generated by Django 5.0.7 on 2024-07-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos_Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=11)),
                ('tipo_documento', models.CharField(max_length=3)),
            ],
        ),
    ]
