# Generated by Django 5.0.7 on 2024-07-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_artistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='infos_artistas',
            options={'verbose_name': 'Info Artista'},
        ),
        migrations.AddField(
            model_name='infos_artistas',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='info_artistas.categoria'),
            preserve_default=False,
        ),
    ]
