# Generated by Django 5.0.7 on 2024-07-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_artistas', '0002_categoria_alter_infos_artistas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos_artistas',
            name='tipo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
