# Generated by Django 5.0.7 on 2024-07-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_artistas', '0003_infos_artistas_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos_artistas',
            name='tipo',
        ),
    ]
